language: node_js

node_js:
  - "0.10"

before_install:
  - npm install -g coffee-script bower gulp
  - bower install
  - npm install

script:
  - gulp assets:js
  - gulp assets:css
  - gulp html
  - gulp assets:img
  - gulp bower:build